# Generated by Django 4.1.1 on 2022-12-17 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('Id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('Id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=50)),
                ('Año', models.DateField()),
                ('Descripcion', models.TextField()),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libros.autor')),
                ('Categoria', models.ManyToManyField(to='Libros.categoria')),
            ],
        ),
        migrations.AddField(
            model_name='autor',
            name='Pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Libros.pais'),
        ),
    ]
